apiVersion: v1
kind: Service
metadata:
  name: syncthing-introducer
  namespace: syncthing
  labels:
    app.kubernetes.io/name: syncthing
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 8384
      targetPort: 8384
      protocol: TCP
    - name: transfer-tcp
      port: 22000
      targetPort: 22000
      protocol: TCP
    - name: transfer-udp
      port: 22000
      targetPort: 22000
      protocol: UDP
    - name: discovery
      port: 21027
      targetPort: 21027
      protocol: UDP
  selector:
    app.kubernetes.io/name: syncthing
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing-transfer-nodeport
  namespace: syncthing
  labels:
    app.kubernetes.io/name: syncthing
spec:
  type: NodePort
  ports:
    - name: transfer-tcp
      port: 22000
      targetPort: 22000
      nodePort: 32000
      protocol: TCP
    - name: transfer-udp
      port: 22000
      targetPort: 22000
      nodePort: 32000
      protocol: UDP
  selector:
    app.kubernetes.io/name: syncthing
